name: vidaplus_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  http: ^1.4.0
  go_router: ^13.0.0
  shared_preferences: ^2.2.2
  flutter:
    sdk: flutter
  provider: ^6.0.0
  file_picker: ^10.2.0
  http_parser: ^4.1.2

  table_calendar: ^3.1.3
  flutter_localizations:
    sdk: flutter



  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

